[package]
name = "portside-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
portside-core = { path = "../portside-core" }
portside-secrets = { path = "../portside-secrets" }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.27.0"
