#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.md from Cargo.lock and package-lock.json.

Lists what ships in the Windows app: the Rust crates the desktop binary links
(normal dependencies only, Windows target) and the npm packages bundled into
the frontend (production dependencies only). Build tools and dev-only packages
are left out because they don't end up in what users install.

Run from the repo root after changing dependencies:

    python3 scripts/third-party-notices.py                  # rewrite THIRD_PARTY_NOTICES.md
    python3 scripts/third-party-notices.py --check          # fail if it's out of date (CI)
    python3 scripts/third-party-notices.py --texts out.txt  # full license texts, for releases

`--texts` copies the LICENSE/COPYING/NOTICE files out of every shipped crate and
npm package (most of these licenses require their text to go with binaries), so
it needs the crates fetched and `npm ci` run. Needs `cargo` on PATH.
"""

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_NOTICES.md"
APP_CRATE = "portside-lite"
TARGET = "x86_64-pc-windows-msvc"

HEADER = """# Third-party notices

Portside Lite is MIT-licensed (see [LICENSE](LICENSE)). It's built on open-source software, and
each component keeps its own license. This file lists everything the installed app contains and
the license each one is under. The full license and notice texts ship with every release, in
`THIRD_PARTY_LICENSES.txt` next to the executable (and in the portable zip).

The MPL-2.0 components (`cssparser`, `cssparser-macros`, `dtoa-short`, `option-ext`, `selectors`)
are used unmodified. Their source code is available from the repositories linked below.

<!-- Generated by scripts/third-party-notices.py. Edit the script, not this file. -->

## Notable components

| Component | Used for | License |
| --- | --- | --- |
| [Tauri](https://tauri.app) | Desktop shell, IPC, tray, dialogs, notifications | MIT OR Apache-2.0 |
| [React](https://react.dev) | User interface | MIT |
| [kube-rs](https://kube.rs) and [k8s-openapi](https://github.com/Arnavion/k8s-openapi) | Kubernetes API client and types | Apache-2.0 |
| [russh](https://github.com/Eugeny/russh) | SSH connections and tunnels | Apache-2.0 |
| [ring](https://github.com/briansmith/ring) and [rustls](https://github.com/rustls/rustls) | TLS and cryptography | Apache-2.0 AND ISC; Apache-2.0 OR ISC OR MIT |
| [SQLite](https://sqlite.org) (via [rusqlite](https://github.com/rusqlite/rusqlite)) | Local storage and full-text log search | Public domain (SQLite); MIT (rusqlite) |
| [Tokio](https://tokio.rs) | Async runtime | MIT |
| [CodeMirror](https://codemirror.net) | YAML editor | MIT |
| [Lucide](https://lucide.dev) | Icons | ISC (parts derived from Feather, MIT) |
| [Zustand](https://github.com/pmndrs/zustand) | UI state | MIT |
| [TanStack Virtual](https://tanstack.com/virtual) | Long log lists | MIT |
| [Tailwind CSS](https://tailwindcss.com) | Styling (build time; the generated CSS ships) | MIT |
| [Rust standard library](https://github.com/rust-lang/rust) | Compiled into the executable | MIT OR Apache-2.0 |

## Not bundled, but used

- **Microsoft Edge WebView2 Runtime.** The installer downloads and installs it if it's missing.
  It's Microsoft software under Microsoft's own license terms, and it isn't redistributed in this
  repository.
- **Inno Setup** builds the installer. Its [license](https://jrsoftware.org/files/is/license.txt)
  allows commercial use. Inno Setup isn't part of the installed app.
- **BusyBox** (`busybox` container image, GPL-2.0) is the default image for the volume file
  browser's helper pod. Your cluster pulls it from its registry. Portside Lite doesn't contain or
  distribute it, and the image can be changed in Settings.

## Acknowledgements

- The color palette is adapted from [Dracula](https://draculatheme.com) (MIT).
- Kubernetes is a registered trademark of The Linux Foundation. k3s is a CNCF project. Portside
  Lite isn't affiliated with or endorsed by either.
"""


def rust_packages():
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--filter-platform", TARGET, "--locked"],
            cwd=ROOT, check=True, capture_output=True, text=True,
        ).stdout
    )
    pkgs = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    start = next(p["id"] for p in meta["packages"] if p["name"] == APP_CRATE)
    seen, stack = set(), [start]
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            # Normal dependencies only: build scripts and dev-deps don't ship.
            if any(k["kind"] is None for k in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    out = []
    for pid in seen:
        p = pkgs[pid]
        if p["source"] is None:  # our own workspace crates
            continue
        directory = Path(p["manifest_path"]).parent
        CRATE_AUTHORS[directory] = p.get("authors") or []
        out.append((p["name"], p["version"], p.get("license") or "", p.get("repository") or "", directory))
    return sorted(out, key=lambda r: (r[0].lower(), r[1]))


def npm_packages():
    lock = json.loads((ROOT / "package-lock.json").read_text(encoding="utf-8"))
    out = []
    for path, p in lock["packages"].items():
        if not path or p.get("dev") or p.get("devOptional") or p.get("link"):
            continue
        name = path.rsplit("node_modules/", 1)[-1]
        lic = p.get("license") or ""
        if isinstance(lic, dict):
            lic = lic.get("type", "")
        out.append((name, p.get("version", ""), lic, f"https://www.npmjs.com/package/{name}", ROOT / path))
    return sorted(set(out), key=lambda r: (r[0].lower(), r[1]))


def table(rows):
    lines = ["| Package | Version | License |", "| --- | --- | --- |"]
    for name, version, lic, url, _ in rows:
        label = f"[{name}]({url})" if url else name
        lines.append(f"| {label} | {version} | {lic or '**unknown**'} |")
    return "\n".join(lines)


def summary(rows):
    counts = Counter(r[2] or "unknown" for r in rows)
    return ", ".join(f"{lic} ({n})" for lic, n in sorted(counts.items(), key=lambda x: (-x[1], x[0])))


LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice|unlicense|copyright)([-._].*)?$", re.I)


def license_files(directory):
    if not directory.is_dir():
        return []
    return sorted(f for f in directory.iterdir() if f.is_file() and LICENSE_FILE.match(f.name))


TEMPLATES = ROOT / "scripts" / "license-templates"
# Crate directory -> authors from cargo metadata (filled by rust_packages).
CRATE_AUTHORS = {}


def authors_of(directory):
    """Copyright holders from package.json or Cargo.toml, for MIT/BSD templates."""
    pj = directory / "package.json"
    if pj.exists():
        a = json.loads(pj.read_text(encoding="utf-8")).get("author")
        a = a.get("name") if isinstance(a, dict) else a
        return a or "the package authors"
    authors = CRATE_AUTHORS.get(directory)
    if authors:
        return ", ".join(re.sub(r"\s*<[^>]*>", "", a) for a in authors)
    return "the package authors"


def template_text(expression, directory):
    """Standard text for a package that ships no license file. For an OR expression one
    option is enough (first one with a template); for AND, all of them."""
    ids = [t for t in re.split(r"[\s()]+|/", expression) if t and t not in ("OR", "AND")]
    if not ids:
        return None
    choose = ids
    texts = []
    for spdx in choose:
        f = TEMPLATES / f"{spdx}.txt"
        if f.exists():
            texts.append(f.read_text(encoding="utf-8").replace("{copyright}", authors_of(directory)).strip())
            if " AND " not in expression:
                break
    if " AND " in expression and len(texts) < len(ids):
        return None
    return "\n\n".join(texts) or None


def write_texts(path, rust, npm):
    """Every package's license/notice files. Identical texts are written once and referenced."""
    rule = "=" * 100
    parts = [
        "Portside Lite: third-party license texts",
        "",
        "License and notice files of the open-source components included in Portside Lite, copied",
        "from each package as published. See THIRD_PARTY_NOTICES.md for the summary.",
        "",
    ]
    seen = {}
    missing = []
    for name, version, lic, url, directory in rust + npm:
        files = license_files(directory)
        parts += [rule, f"{name} {version}", f"License: {lic or 'unknown'}"] + ([f"Source: {url}"] if url else []) + [rule, ""]
        if not files:
            text = template_text(lic, directory)
            if text is None:
                missing.append(name)
                parts += [f"The package doesn't include a license file. It's published under {lic or 'an unknown license'}; see {url or 'its repository'}.", ""]
            else:
                parts += ["The package doesn't include a license file; this is the standard text of its declared license.", "", text, ""]
        for f in files:
            text = f.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n").strip()
            if text in seen:
                parts += [f"[{f.name}: same text as {seen[text]} above]", ""]
            else:
                seen[text] = f"{name} {version} ({f.name})"
                parts += [f"--- {f.name} ---", "", text, ""]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {path}: {len(rust) + len(npm)} packages, {len(seen)} distinct texts")
    if missing:
        print("No license file in: " + ", ".join(missing), file=sys.stderr)


def notices(rust, npm):
    return "\n".join([
        HEADER.rstrip(),
        "",
        f"## Rust crates ({len(rust)})",
        "",
        f"Linked into the desktop app. Licenses: {summary(rust)}.",
        "",
        table(rust),
        "",
        f"## npm packages ({len(npm)})",
        "",
        f"Bundled into the user interface. Licenses: {summary(npm)}.",
        "",
        table(npm),
        "",
    ])


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if THIRD_PARTY_NOTICES.md is out of date")
    ap.add_argument("--texts", metavar="PATH", help="also write the full license texts to PATH")
    args = ap.parse_args()

    rust, npm = rust_packages(), npm_packages()
    unknown = [r[0] for r in rust + npm if not r[2]]
    if unknown:
        print("No license metadata for: " + ", ".join(unknown), file=sys.stderr)
    body = notices(rust, npm)
    if args.check:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if current != body:
            sys.exit(f"{OUT.name} is out of date. Run: python3 scripts/third-party-notices.py")
        print(f"{OUT.name} is up to date")
    else:
        OUT.write_text(body, encoding="utf-8", newline="\n")
        print(f"Wrote {OUT.name}: {len(rust)} crates, {len(npm)} npm packages")
    if args.texts:
        write_texts(args.texts, rust, npm)


if __name__ == "__main__":
    main()
